# Generated by Django 4.0.10 on 2023-07-02 10:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0009_alter_audio_name_alter_audio_path_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='annotationvideo',
            old_name='Video',
            new_name='video',
        ),
        migrations.CreateModel(
            name='VideoResultAnnotation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video_name', models.CharField(max_length=250)),
                ('note_name', models.CharField(max_length=250)),
                ('note_emoji', models.CharField(max_length=250)),
                ('creation_date', models.DateTimeField(auto_now_add=True)),
                ('video', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='note_finale', to='notes.video')),
            ],
            options={
                'ordering': ['-creation_date'],
            },
        ),
    ]
