# Generated by Django 4.0.10 on 2023-07-04 10:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0011_alter_video_options_remove_audio_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='videoresultannotation',
            name='video',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='note_video_finale', to='notes.video'),
        ),
    ]
