# Generated by Django 4.0.10 on 2023-07-04 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0012_alter_videoresultannotation_video'),
    ]

    operations = [
        migrations.AlterField(
            model_name='audio',
            name='number',
            field=models.CharField(max_length=250),
        ),
        migrations.AlterField(
            model_name='video',
            name='number',
            field=models.CharField(max_length=250),
        ),
    ]
