# Generated by Django 4.1.4 on 2023-08-07 16:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("notes", "0014_coordinatevideo"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="coordinate",
            name="town",
        ),
        migrations.RemoveField(
            model_name="coordinatevideo",
            name="town",
        ),
    ]
